env:
  contexts:
    - name: "Forum App Authenticated"
      urls:
        - "http://localhost:8000"
      includePaths:
        - "http://localhost:8000/.*"
      excludePaths:
        - "http://localhost:8000/logout.*"
        - "http://localhost:8000/static/.*"
        - "http://localhost:8000/uploads/.*"
      authentication:
        method: "form"
        parameters:
          loginUrl: "http://localhost:8000/login"
          loginRequestData: "username={%username%}&password={%password%}"
        verification:
          method: "response"
          loggedInRegex: "\\Qusername\\E"
          loggedOutRegex: "\\Qlogin\\E"
      users:
        - name: "testuser"
          credentials:
            username: "admin"
            password: "Admin@123"
      sessionManagement:
        method: "cookie"
        parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  - type: spider
    parameters:
      context: "Forum App Authenticated"
      user: "testuser"
      maxDuration: 5
      maxDepth: 10
      maxChildren: 20
      acceptCookies: true
      handleODataParametersVisited: false

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  - type: activeScan
    parameters:
      context: "Forum App Authenticated"
      user: "testuser"
      maxRuleDurationInMins: 5
      maxScanDurationInMins: 15
      addQueryParam: false
      defaultPolicy: "Default Policy"
      delayInMs: 0
      handleAntiCSRFTokens: true
      injectPluginIdInHeader: false
      scanHeadersAllRequests: true

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "zap-reports"
      reportFile: "zap-authenticated-report.html"
      reportTitle: "ZAP Authenticated Scan Report - Forum App"
      reportDescription: "Full authenticated security scan of the Forum application"

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "zap-reports"
      reportFile: "zap-authenticated-report.json"

  - type: report
    parameters:
      template: "traditional-md"
      reportDir: "zap-reports"
      reportFile: "zap-authenticated-report.md"
